name: Whatsapp Stable
version: "1.0.3"
slug: whatsapp_stable
description: Stable WhatsApp add-on for Home Assistant
url: "https://github.com/arormoser/ha-addons/tree/main/whatsapp_addon"
homeassistant_api: true
hassio_api: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
  - media:rw
options:
  clients:
    - default
schema:
  clients:
    - str
